### ISSUE TITLE
java.lang.NoClassDefFoundError: io.reactivex.Flowable

### ISSUE THREAD

**Issue by yleyvag** [tbruyelle/RxPermissions#185]
I'm working with Android Studio 3.0 and Gradle 4.1. 

On my gradle:

`implementation 'com.google.dagger:dagger:2.6.1'`
`implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'`
`implementation 'io.reactivex.rxjava2:rxjava:2.1.6'`
`implementation 'com.android.support:multidex:1.0.2'`
`implementation 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.4@aar'`
`implementation 'com.google.dagger:dagger-compiler:2.6.1'`
`annotationProcessor 'com.google.dagger:dagger-compiler:2.6.1'`
`implementation 'com.jakewharton:butterknife:8.8.1'`
`annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'`

On my Activity:
`...`
`RxPermissions rxPermissions = new RxPermissions(this);`
       ` rxPermissions.request(Manifest.permission.WRITE_EXTERNAL_STORAGE)`
               ` .subscribe(granted -> {`
                  `  if (granted)`
            `        {`
             `           Toast.makeText(this, "granted", Toast.LENGTH_SHORT).show();`
            `        }`
      `              else`
            `        {`
                `        Toast.makeText(this, "rejected", Toast.LENGTH_SHORT).show();`
    `                }`
          `      });`
`...`

I'm receiving this exception:

java.lang.NoClassDefFoundError: io.reactivex.Flowable
at io.reactivex.Observable.bufferSize(Observable.java:165)
at io.reactivex.Observable.flatMap(Observable.java:7520)
at io.reactivex.Observable.merge(Observable.java:2837)
at com.tbruyelle.rxpermissions2.RxPermissions.oneOf(RxPermissions.java:165)
at com.tbruyelle.rxpermissions2.RxPermissions.request(RxPermissions.java:143)
at com.tbruyelle.rxpermissions2.RxPermissions.access$000(RxPermissions.java:33)
at com.tbruyelle.rxpermissions2.RxPermissions$1.apply(RxPermissions.java:79)
at io.reactivex.Observable.compose(Observable.java:6018)
at com.tbruyelle.rxpermissions2.RxPermissions.request(RxPermissions.java:127)
at com.x.x.x.x.x.SubmitAdActivity.onPickAttachment(SubmitAdActivity.java:341)
at com.x.x.x.x.x.BottomSubmitBar.takeAttachment(BottomSubmitBar.java:148)
at com.x.x.x.x.x.BottomSubmitBar.onClick(BottomSubmitBar.java:123)
at android.view.View.performClick(View.java:5697)
at android.view.View$PerformClick.run(View.java:22526)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by yleyvag** [comment]
The problem get solved adding
`implementation` 'org.reactivestreams:reactive-streams:1.0.1'``
